-- Diecast Kingdoms V2.0.0: server-timestamped project history and Halloween leaderboard.
-- Run once in the Supabase SQL editor before publishing index.html.

create table if not exists public.project_events (
    id bigint generated by default as identity primary key,
    project_id text not null references public.projects(id) on delete cascade,
    event_type text not null,
    from_status text,
    to_status text,
    event_at timestamptz not null default now()
);

create index if not exists project_events_project_time_idx
    on public.project_events (project_id, event_at desc);

alter table public.project_events enable row level security;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'project_events'
          and policyname = 'Allow public project event reads'
    ) then
        create policy "Allow public project event reads"
            on public.project_events for select to anon, authenticated using (true);
    end if;
end
$$;

grant select on public.project_events to anon, authenticated;

create or replace function public.track_project_events()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    evidence_changed boolean := false;
begin
    if tg_op = 'INSERT' then
        insert into public.project_events (project_id, event_type, to_status)
        values (new.id, 'suggestion_submitted', new.status);
        return new;
    end if;

    evidence_changed :=
        old.image_after_preview is distinct from new.image_after_preview
        or old.images_after is distinct from new.images_after
        or old.video_after_url is distinct from new.video_after_url
        or old.expense is distinct from new.expense
        or old.actual_result is distinct from new.actual_result
        or old.updated_at is distinct from new.updated_at;

    if new.status = 'Evidence' and (old.status is distinct from new.status or evidence_changed) then
        insert into public.project_events (project_id, event_type, from_status, to_status)
        values (
            new.id,
            case when old.status = 'Evidence' then 'evidence_updated' else 'evidence_submitted' end,
            old.status,
            new.status
        );
    elsif old.status is distinct from new.status then
        insert into public.project_events (project_id, event_type, from_status, to_status)
        values (new.id, 'status_changed', old.status, new.status);
    end if;

    if old.comment is distinct from new.comment or old.target_comment is distinct from new.target_comment then
        insert into public.project_events (project_id, event_type, from_status, to_status)
        values (new.id, 'comment_updated', old.status, new.status);
    end if;

    return new;
end;
$$;

revoke all on function public.track_project_events() from public;
grant execute on function public.track_project_events() to anon, authenticated;

drop trigger if exists projects_track_events on public.projects;
create trigger projects_track_events
    after insert or update on public.projects
    for each row execute function public.track_project_events();

create table if not exists public.halloween_game_scores (
    employee_key text primary key,
    employee_id text not null,
    employee_name text not null,
    kingdom text not null,
    score integer not null check (score > 0),
    kills integer not null default 0 check (kills >= 0),
    max_combo integer not null default 0 check (max_combo >= 0),
    best_played_at timestamptz not null default now(),
    constraint halloween_game_valid_kingdom check (
        kingdom in ('เบสเซนตร้า', 'แคสเทอเรีย', 'แบลงค์ไฮม์การ์ด', 'แมคชีนโพลิส', 'ไฟนัลธรอน')
    )
);

alter table public.halloween_game_scores enable row level security;
revoke all on public.halloween_game_scores from public, anon, authenticated;

create or replace function public.get_halloween_game_leaderboard()
returns jsonb
language sql
security definer
set search_path = public
as $$
    with ranked as (
        select
        row_number() over (order by score desc, best_played_at asc, employee_key asc) as rank,
            employee_id,
            employee_name,
            kingdom,
            score,
            kills,
            max_combo
        from public.halloween_game_scores
    )
    select jsonb_build_object(
        'rows', coalesce(jsonb_agg(jsonb_build_object(
            'rank', rank,
            'employeeId', employee_id,
            'name', employee_name,
            'sect', kingdom,
            'score', score,
            'kills', kills,
            'combo', max_combo
        ) order by rank) filter (where rank <= 8), '[]'::jsonb)
    )
    from ranked;
$$;

create or replace function public.submit_halloween_game_score(
    p_employee_id text,
    p_employee_name text,
    p_kingdom text,
    p_score integer,
    p_kills integer,
    p_max_combo integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_employee_id text := btrim(coalesce(p_employee_id, ''));
    v_employee_name text := left(btrim(coalesce(p_employee_name, 'หมอผีน้อย')), 14);
    v_key text;
    v_best public.halloween_game_scores%rowtype;
    v_rank integer;
    v_rows jsonb;
begin
    if timezone('Asia/Bangkok', now()) < timestamp '2026-09-27 00:00:00'
       or timezone('Asia/Bangkok', now()) >= timestamp '2026-10-31 00:00:00' then
        raise exception 'กิจกรรมฮาโลวีนยังไม่เปิดหรือปิดกิจกรรมแล้ว';
    end if;
    if length(v_employee_id) < 1 or length(v_employee_id) > 20 then
        raise exception 'รหัสพนักงานไม่ถูกต้อง';
    end if;
    if v_employee_name = '' then v_employee_name := 'หมอผีน้อย'; end if;
    if p_kingdom not in ('เบสเซนตร้า', 'แคสเทอเรีย', 'แบลงค์ไฮม์การ์ด', 'แมคชีนโพลิส', 'ไฟนัลธรอน') then
        raise exception 'อาณาจักรไม่ถูกต้อง';
    end if;
    if coalesce(p_score, 0) <= 0 or coalesce(p_kills, 0) < 0 or coalesce(p_max_combo, 0) < 0 then
        raise exception 'คะแนนไม่ถูกต้อง';
    end if;

    v_key := lower(v_employee_id);
    insert into public.halloween_game_scores (
        employee_key, employee_id, employee_name, kingdom, score, kills, max_combo
    ) values (
        v_key, v_employee_id, v_employee_name, p_kingdom, p_score, p_kills, p_max_combo
    )
    on conflict (employee_key) do update set
        employee_id = excluded.employee_id,
        employee_name = excluded.employee_name,
        kingdom = excluded.kingdom,
        score = excluded.score,
        kills = excluded.kills,
        max_combo = excluded.max_combo,
        best_played_at = now()
    where excluded.score > public.halloween_game_scores.score;

    select * into v_best
    from public.halloween_game_scores
    where employee_key = v_key;

    select count(*)::integer + 1 into v_rank
    from public.halloween_game_scores
    where score > v_best.score
       or (score = v_best.score and best_played_at < v_best.best_played_at)
       or (score = v_best.score and best_played_at = v_best.best_played_at and employee_key < v_key);

    select coalesce(jsonb_agg(jsonb_build_object(
        'rank', ranked.rank,
        'employeeId', ranked.employee_id,
        'name', ranked.employee_name,
        'sect', ranked.kingdom,
        'score', ranked.score,
        'kills', ranked.kills,
        'combo', ranked.max_combo
    ) order by ranked.rank), '[]'::jsonb)
    into v_rows
    from (
        select
            row_number() over (order by score desc, best_played_at asc, employee_key asc) as rank,
            employee_id,
            employee_name, kingdom, score, kills, max_combo
        from public.halloween_game_scores
        order by score desc, best_played_at asc, employee_key asc
        limit 8
    ) ranked;

    return jsonb_build_object(
        'result', jsonb_build_object(
            'rank', v_rank,
            'record', jsonb_build_object('score', v_best.score),
            'rows', v_rows
        ),
        'rows', v_rows
    );
end;
$$;

revoke all on function public.get_halloween_game_leaderboard() from public;
revoke all on function public.submit_halloween_game_score(text, text, text, integer, integer, integer) from public;
grant execute on function public.get_halloween_game_leaderboard() to anon, authenticated;
grant execute on function public.submit_halloween_game_score(text, text, text, integer, integer, integer) to anon, authenticated;
